//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperaciónOrbita.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaciones
    {
        public int Id { get; set; }
        public Nullable<int> MisionId { get; set; }
        public Nullable<int> RecursoId { get; set; }
    
        public virtual Misiones Misiones { get; set; }
        public virtual Recursos Recursos { get; set; }
    }
}
