//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperaciónOrbita.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misiones
    {
        public Misiones()
        {
            this.Asignaciones = new HashSet<Asignaciones>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Prioridad { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Estado { get; set; }
        public Nullable<int> ResponsableId { get; set; }
    
        public virtual ICollection<Asignaciones> Asignaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
