//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperaciónOrbita.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrbitaDBEntities : DbContext
    {
        public OrbitaDBEntities()
            : base("name=OrbitaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asignaciones> Asignaciones { get; set; }
        public DbSet<Misiones> Misiones { get; set; }
        public DbSet<Recursos> Recursos { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
