//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperaciónOrbita.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recursos
    {
        public Recursos()
        {
            this.Asignaciones = new HashSet<Asignaciones>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Modelo { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Autonomia { get; set; }
        public Nullable<decimal> Alcance { get; set; }
        public Nullable<decimal> CostoPorHora { get; set; }
        public Nullable<decimal> CapacidadCarga { get; set; }
        public Nullable<decimal> CostoPorKilometro { get; set; }
        public Nullable<int> CantidadSensores { get; set; }
        public Nullable<decimal> ConsumoEnergetico { get; set; }
        public Nullable<decimal> CostoDiario { get; set; }
    
        public virtual ICollection<Asignaciones> Asignaciones { get; set; }
    }
}
